map shift+space send_text all \x1b[32;2u
map ctrl+shift+y send_text all \x1b[89;6u
map ctrl+shift+h send_text all \x1b[72;6u
map ctrl+shift+j send_text all \x1b[74;6u
map ctrl+shift+k send_text all \x1b[75;6u
map ctrl+shift+l send_text all \x1b[76;6u
map ctrl+shift+n send_text all \x1b[78;6u
map ctrl+shift+p send_text all \x1b[80;6
map ctrl+1 send_text application \x14\x31
map ctrl+2 send_text application \x14\x32
map ctrl+3 send_text application \x14\x33
map ctrl+4 send_text application \x14\x34
map ctrl+5 send_text application \x14\x35
map ctrl+6 send_text application \x14\x36
map ctrl+7 send_text application \x14\x37
map ctrl+8 send_text application \x14\x38
map ctrl+9 send_text application \x14\x39u
map ctrl+minus change_font_size all -1.0
map ctrl+equal change_font_size all +1.0
map ctrl+backspace send_text all \x17
