#! /usr/bin/env bash 

workspace()
{
	name=1
	for monitor in 'bspc qeury -M'; do 
 	 	bspc monitor $(monitor) -n "$name" -d "一" "二" "三" "四" "五" "六" "七" "八" "九" "十"
		let name++
	done
}
workspace
bspc config border_width 	0
bspc config window_gap 	 	10


bspc config split_ratio 	0.5
bspc config single_monocle  	false
bspc config borderless_monocle 	true
bspc config focus_follows_pointer true 
bspc config gapless_monocle 	true 

bspc config focused_border_color 	"#BD93F9"
bspc config normal_border_color 	"#282A36"
bspc config active_border_color 	"#8BE0FD"
bspc config presel_feedback_color 	"#50FA7B"

dunst &
~/.config/polybar/launch.sh --hack
picom --experimental-backends &
feh --bg-fill ~/wallpaper.jpg
sxhkd &
komorebi &
