#! /usr/bin/env bash

workspace() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "$monitor" -n "$name" -d "一" "二" "三" "四" "五"
		((name++))
	done
}
workspace
bspc config border_width 3
bspc config window_gap 10

bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focused_border_color "#BD93F9"
bspc config normal_border_color "#282A36"
bspc config active_border_color "#8BE0FD"
bspc config presel_feedback_color "#50FA7B"

xsetroot -cursor_name left_ptr
dunst &
~/.config/polybar/launch.sh &
picom --experimental-backends &
~/.fehbg
# background-generate > /dev/null &
flameshot &
sxhkd &
if ! pgrep -x ibus-daemon >/dev/null; then
	ibus-setup
fi
