#!/bin/sh
tmpfile="/tmp/bspwm-hidden"
desktop=$(bspc query -D -d focused)
bspc query -N -n .hidden -d "$desktop" > $tmpfile
case $1 in 
--hide )
	bspc node focused -g hidden=on ;;
--showall )
  while read -r nodes
  do
    bspc node "$nodes" -g hidden=off
  done < $tmpfile
esac
